## Fortono to output kai pairno tin lista apo ta unique transcripts gia na kano request meta

In [1]:
import pandas as pd

df = pd.read_csv(
    'outputfull.tsv',
    sep='\t',
    comment='#',
    header=None
)

# Find the header line (starts with single '#')
with open('output.tsv') as f:
    for line in f.readlines():
        if line.startswith('#') and not line.startswith('##'):
            header = line.lstrip('#').strip().split('\t')
            break

df.columns = header # type: ignore

In [2]:
len(df)

49318303

In [5]:
df = df[df['Consequence'].str.contains('3_prime_UTR_variant')]

In [6]:
df

,Uploaded_variation,Location,Allele,Gene,Feature,Feature_type,Consequence,cDNA_position,CDS_position,Protein_position,Amino_acids,Codons,Existing_variation,Extra
11793,chr1_71298_G/A,chr1:71298,A,ENSG00000186092,ENST00000641515,Transcript,3_prime_UTR_variant,2331,-,-,-,-,-,IMPACT=MODIFIER;STRAND=1
74226,rs56972694,chr1:943527-943529,-,ENSG00000188976,ENST00000870725,Transcript,3_prime_UTR_variant,3483-3485,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1
74292,rs6605067,chr1:944296,A,ENSG00000188976,ENST00000327044,Transcript,3_prime_UTR_variant,2664,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1
74293,rs6605067,chr1:944296,A,ENSG00000187634,ENST00000341065,Transcript,3_prime_UTR_variant,1912,-,-,-,-,-,IMPACT=MODIFIER;STRAND=1;FLAGS=cds_start_NF
74294,rs6605067,chr1:944296,A,ENSG00000187634,ENST00000342066,Transcript,3_prime_UTR_variant,2279,-,-,-,-,-,IMPACT=MODIFIER;STRAND=1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49287890,chrY_5740126_T/TAC,chrY:5740125-5740126,AC,ENSG00000099715,ENST00000698851,Transcript,3_prime_UTR_variant,6451-6452,-,-,-,-,-,IMPACT=MODIFIER;STRAND=1
49287891,chrY_5740137_T/C/*,chrY:5740137,C,ENSG00000099715,ENST00000400457,Transcript,3_prime_UTR_variant,6952,-,-,-,-,-,IMPACT=MODIFIER;STRAND=1
49287892,chrY_5740137_T/C/*,chrY:5740137,C,ENSG00000099715,ENST00000698851,Transcript,3_prime_UTR_variant,6463,-,-,-,-,-,IMPACT=MODIFIER;STRAND=1
49287893,rs2556915,chrY:5740179,T,ENSG00000099715,ENST00000400457,Transcript,3_prime_UTR_variant,6994,-,-,-,-,-,IMPACT=MODIFIER;STRAND=1
49287894,rs2556915,chrY:5740179,T,ENSG00000099715,ENST00000698851,Transcript,3_prime_UTR_variant,6505,-,-,-,-,-,IMPACT=MODIFIER;STRAND=1

In [4]:
transcripts = df['Feature'].drop_duplicates().to_list()
transcripts

['ENST00000641515',
 'ENST00000870725',
 'ENST00000327044',
 'ENST00000341065',
 'ENST00000342066',
 'ENST00000616016',
 'ENST00000618323',
 'ENST00000870726',
 'ENST00000870727',
 'ENST00000870728',
 'ENST00000870729',
 'ENST00000870730',
 'ENST00000870731',
 'ENST00000870732',
 'ENST00000870733',
 'ENST00000870734',
 'ENST00000870735',
 'ENST00000870736',
 'ENST00000870737',
 'ENST00000870738',
 'ENST00000870739',
 'ENST00000934932',
 'ENST00000934933',
 'ENST00000934934',
 'ENST00000934935',
 'ENST00000934936',
 'ENST00000934937',
 'ENST00000934938',
 'ENST00000934939',
 'ENST00000934940',
 'ENST00000934941',
 'ENST00000934942',
 'ENST00000934943',
 'ENST00000934944',
 'ENST00000934945',
 'ENST00000934946',
 'ENST00000934947',
 'ENST00000934948',
 'ENST00000934949',
 'ENST00000934950',
 'ENST00000934951',
 'ENST00000934952',
 'ENST00000934953',
 'ENST00000934954',
 'ENST00000934955',
 'ENST00000934956',
 'ENST00000934957',
 'ENST00000934958',
 'ENST00000934959',
 'ENST00000968542',
 'ENST00000968543',
 'ENST00000968544',
 'ENST00000968805',
 'ENST00000968806',
 'ENST00000968807',
 'ENST00000968808',
 'ENST00000968809',
 'ENST00000968810',
 'ENST00000968811',
 'ENST00000968812',
 'ENST00000968813',
 'ENST00000968814',
 'ENST00000968815',
 'ENST00000968816',
 'ENST00000968817',
 'ENST00000968818',
 'ENST00000968819',
 'ENST00000968820',
 'ENST00000968821',
 'ENST00000968822',
 'ENST00000968823',
 'ENST00000968824',
 'ENST00000338591',
 'ENST00000887516',
 'ENST00000887517',
 'ENST00000935109',
 'ENST00000935110',
 'ENST00000955597',
 'ENST00000955598',
 'ENST00000379410',
 'ENST00000880608',
 'ENST00000880609',
 'ENST00000880610',
 'ENST00000880611',
 'ENST00000880612',
 'ENST00000959612',
 'ENST00000959613',
 'ENST00000341290',
 'ENST00000433179',
 'ENST00000880867',
 'ENST00000880868',
 'ENST00000880869',
 'ENST00000880870',
 'ENST00000959770',
 'ENST00000959771',
 'ENST00000959772',
 'ENST00000959773',
 'ENST00000379370',
 'ENST00000620552',
 'ENST00000651234',
 'ENST00000652369',
 'ENST00000453464',
 'ENST00000379325',
 'ENST00000379339',
 'ENST00000421241',
 'ENST00000467751',
 'ENST00000477196',
 'ENST00000871969',
 'ENST00000871970',
 'ENST00000871971',
 'ENST00000871972',
 'ENST00000871973',
 'ENST00000871974',
 'ENST00000871975',
 'ENST00000871976',
 'ENST00000871977',
 'ENST00000871978',
 'ENST00000871979',
 'ENST00000871981',
 'ENST00000871982',
 'ENST00000871983',
 'ENST00000934528',
 'ENST00000934529',
 'ENST00000934530',
 'ENST00000934531',
 'ENST00000934532',
 'ENST00000934533',
 'ENST00000934534',
 'ENST00000934535',
 'ENST00000934536',
 'ENST00000962840',
 'ENST00000962841',
 'ENST00000962842',
 'ENST00000962843',
 'ENST00000962845',
 'ENST00000962846',
 'ENST00000962847',
 'ENST00000962848',
 'ENST00000962849',
 'ENST00000458452',
 'ENST00000527098',
 'ENST00000532772',
 'ENST00000531377',
 'ENST00000429572',
 'ENST00000430786',
 'ENST00000531019',
 'ENST00000343938',
 'ENST00000900278',
 'ENST00000900279',
 'ENST00000900280',
 'ENST00000900281',
 'ENST00000900282',
 'ENST00000900283',
 'ENST00000956293',
 'ENST00000339381',
 'ENST00000378888',
 'ENST00000378891',
 'ENST00000874577',
 'ENST00000911402',
 'ENST00000954312',
 'ENST00000954313',
 'ENST00000954314',
 'ENST00000954315',
 'ENST00000309212',
 'ENST00000342753',
 'ENST00000445648',
 'ENST00000477278',
 'ENST00000897927',
 'ENST00000953649',
 'ENST00000953650',
 'ENST00000953651',
 'ENST00000400809',
 'ENST00000378821',
 'ENST00000338660',
 'ENST00000476993',
 'ENST00000895634',
 'ENST00000895635',
 'ENST00000339113',
 'ENST00000378755',
 'ENST00000378756',
 'ENST00000400830',
 'ENST00000536055',
 'ENST00000904938',
 'ENST00000936381',
 'ENST00000936382',
 'ENST00000936383',
 'ENST00000936384',
 'ENST00000936385',
 'ENST00000490017',
 'ENST00000341832',
 'ENST00000892873',
 'ENST00000892875',
 'ENST00000892876',
 'ENST00000931742',
 'ENST00000611150',
 'ENST00000615951',
 'ENST00000611123',
 'ENST00000617444',
 'ENST00000904336',
 'ENST00000904337',
 'ENST00000904338',
 'ENST00000911898',
 'ENST00000911899',
 'ENST00000911901',
 'ENST00000904339',
 'ENST00000904340',
 'ENST00000911900',
 'ENST00000956985',
 'ENST00000404249',
 'ENST00000893735',
 'ENST00000893736',
 'ENST00000460465',
 'ENST00000509982',
 'ENST00000341426',
 'ENST00000341991',
 'ENST00000378625',
 'ENST00000886130',
 'ENST00000886131',
 'ENST00000886132',
 'ENST00000886133',
 'ENST00000886134',
 'ENST00000886135',
 'ENST00000886136',
 'ENST00000886137',
 'ENST00000886138',
 'ENST00000886139',
 'ENST00000886140',
 'ENST00000886141',
 'ENST00000886142',
 'ENST00000886143',
 'ENST00000886144',
 'ENST00000931657',
 'ENST00000931658',
 'ENST00000931659',
 'ENST00000931660',
 'ENST00000931662',
 'ENST00000953973',
 'ENST00000953974',
 'ENST00000342348',
 'ENST00000931661',
 'ENST00000931663',
 'ENST00000953975',
 'ENST00000498806',
 'ENST00000469045',
 'ENST00000489538',
 'ENST00000497186',
 'ENST00000307786',
 'ENST00000470931',
 'ENST00000493964',
 'ENST00000682832',
 'ENST00000639045',
 'ENST00000378536',
 'ENST00000851187',
 'ENST00000874224',
 'ENST00000874225',
 'ENST00000378531',
 'ENST00000874226',
 'ENST00000874227',
 'ENST00000874228',
 'ENST00000963688',
 'ENST00000963689',
 'ENST00000963690',
 'ENST00000449373',
 'ENST00000378525',
 'ENST00000288774',
 'ENST00000378513',
 'ENST00000447513',
 'ENST00000605895',
 'ENST00000650293',
 'ENST00000874469',
 'ENST00000874470',
 'ENST00000874471',
 'ENST00000874472',
 'ENST00000874473',
 'ENST00000874474',
 'ENST00000874475',
 'ENST00000874476',
 'ENST00000874692',
 'ENST00000920616',
 'ENST00000920617',
 'ENST00000920618',
 'ENST00000920619',
 'ENST00000920620',
 'ENST00000954665',
 'ENST00000507596',
 'ENST00000874693',
 'ENST00000502666',
 'ENST00000514502',
 'ENST00000378453',
 'ENST00000355716',
 'ENST00000860781',
 'ENST00000860782',
 'ENST00000860783',
 'ENST00000860784',
 'ENST00000860785',
 'ENST00000860786',
 'ENST00000860787',
 'ENST00000860788',
 'ENST00000860789',
 'ENST00000860790',
 'ENST00000860791',
 'ENST00000972443',
 'ENST00000972444',
 'ENST00000972445',
 'ENST00000972446',
 'ENST00000482602',
 'ENST00000378412',
 'ENST00000378424',
 'ENST00000378425',
 'ENST00000378427',
 'ENST00000419916',
 'ENST00000444521',
 'ENST00000471840',
 'ENST00000877697',
 'ENST00000877698',
 'ENST00000923153',
 'ENST00000923154',
 'ENST00000971684',
 'ENST00000463591',
 'ENST00000270722',
 'ENST00000378371',
 'ENST00000378373',
 'ENST00000378378',
 'ENST00000868561',
 'ENST00000868562',
 'ENST00000868563',
 'ENST00000868564',
 'ENST00000943437',
 'ENST00000344579',
 'ENST00000378344',
 'ENST00000888361',
 'ENST00000378288',
 'ENST00000378295',
 'ENST00000604074',
 'ENST00000713570',
 'ENST00000713572',
 'ENST00000908821',
 'ENST00000917568',
 'ENST00000917569',
 'ENST00000462521',
 'ENST00000863967',
 'ENST00000378251',
 'ENST00000855510',
 'ENST00000855511',
 'ENST00000855512',
 'ENST00000931368',
 'ENST00000931369',
 'ENST00000931370',
 'ENST00000931371',
 'ENST00000971585',
 'ENST00000378230',
 'ENST00000674558',
 'ENST00000674623',
 'ENST00000674985',
 'ENST00000675108',
 'ENST00000675200',
 'ENST00000675666',
 'ENST00000675677',
 'ENST00000675750',
 'ENST00000676009',
 'ENST00000676052',
 'ENST00000674544',
 'ENST00000675375',
 'ENST00000894371',
 'ENST00000894372',
 'ENST00000894373',
 'ENST00000923945',
 'ENST00000923946',
 'ENST00000923947',
 'ENST00000955290',
 'ENST00000955291',
 'ENST00000428079',
 'ENST00000339350',
 'ENST00000378206',
 'ENST00000468793',
 'ENST00000475969',
 'ENST00000477548',
 'ENST00000491998',
 'ENST00000338895',
 'ENST00000378209',
 'ENST00000894547',
 'ENST00000919095',
 'ENST00000361605',
 'ENST00000679703',
 'ENST00000679946',
 'ENST00000680054',
 'ENST00000680169',
 'ENST00000680279',
 'ENST00000681823',
 'ENST00000880749',
 'ENST00000378191',
 'ENST00000378169',
 'ENST00000489180',
 'ENST00000466897',
 'ENST00000666299',
 'ENST00000462676',
 'ENST00000662815',
 'ENST00000671076',
 'ENST00000602612',
 'ENST00000668559',
 'ENST00000653262',
 'ENST00000164247',
 'ENST00000341524',
 'ENST00000352527',
 'ENST00000378083',
 'ENST00000378097',
 'ENST00000428161',
 'ENST00000662363',
 'ENST00000666163',
 'ENST00000669250',
 'ENST00000671676',
 'ENST00000262450',
 'ENST00000377999',
 'ENST00000462991',
 'ENST00000475121',
 'ENST00000496404',
 'ENST00000343813',
 'ENST00000489498',
 'ENST00000875198',
 'ENST00000944941',
 'ENST00000377893',
 'ENST00000937749',
 'ENST00000937750',
 'ENST00000957092',
 'ENST00000636330',
 'ENST00000377705',
 'ENST00000870262',
 'ENST00000870263',
 'ENST00000870264',
 'ENST00000870265',
 'ENST00000925477',
 'ENST00000925478',
 'ENST00000377663',
 'ENST00000377648',
 'ENST00000961800',
 'ENST00000472925',
 'ENST00000487819',
 'ENST00000377627',
 'ENST00000377577',
 'ENST00000451196',
 'ENST00000685129',
 'ENST00000686243',
 'ENST00000688524',
 'ENST00000885067',
 'ENST00000885068',
 'ENST00000885069',
 'ENST00000885070',
 'ENST00000885071',
 'ENST00000939001',
 'ENST00000939002',
 'ENST00000939003',
 'ENST00000954225',
 'ENST00000954226',
 'ENST00000294401',
 'ENST00000885072',
 'ENST00000482934',
 'ENST00000700416',
 'ENST00000495233',
 'ENST00000700414',
 'ENST00000710284',
 'ENST00000710285',
 'ENST00000303635',
 'ENST00000476864',
 'ENST00000490905',
 'ENST00000700415',
 'ENST00000700417',
 'ENST00000700419',
 'ENST00000700420',
 'ENST00000700421',
 'ENST00000700423',
 'ENST00000700424',
 'ENST00000700425',
 'ENST00000700445',
 'ENST00000700448',
 'ENST00000700449',
 'ENST00000054666',
 'ENST00000361923',
 'ENST00000377532',
 'ENST00000613533',
 'ENST00000614998',
 'ENST00000893509',
 'ENST00000893510',
 'ENST00000893511',
 'ENST00000893512',
 'ENST00000917933',
 'ENST00000961535',
 'ENST00000961536',
 'ENST00000961537',
 'ENST00000961538',
 'ENST00000961539',
 'ENST00000377507',
 'ENST00000289877',
 'ENST00000471889',
 'ENST00000876632',
 'ENST00000876633',
 'ENST00000337907',
 'ENST00000377464',
 'ENST00000400908',
 'ENST00000465125',
 'ENST00000864419',
 'ENST00000659924',
 'ENST00000704049',
 'ENST00000480186',
 'ENST00000377443',
 'ENST00000377424',
 'ENST00000941832',
 'ENST00000941833',
 'ENST00000941834',
 'ENST00000377414',
 'ENST00000377411',
 'ENST00000961135',
 'ENST00000377403',
 'ENST00000602477',
 'ENST00000891474',
 'ENST00000891475',
 'ENST00000891476',
 'ENST00000919134',
 'ENST00000948983',
 'ENST00000948986',
 'ENST00000948987',
 'ENST00000948988',
 'ENST00000948989',
 'ENST00000328089',
 'ENST00000357898',
 'ENST00000852374',
 'ENST00000852375',
 'ENST00000852376',
 'ENST00000852377',
 'ENST00000852378',
 'ENST00000946663',
 'ENST00000946664',
 'ENST00000340381',
 'ENST00000416541',
 'ENST00000857597',
 'ENST00000928149',
 'ENST00000928150',
 'ENST00000377346',
 'ENST00000481137',
 'ENST00000698709',
 'ENST00000698710',
 'ENST00000698712',
 'ENST00000698713',
 'ENST00000698714',
 'ENST00000698715',
 'ENST00000698716',
 'ENST00000892287',
 'ENST00000892288',
 'ENST00000892289',
 'ENST00000892290',
 'ENST00000932635',
 'ENST00000932636',
 'ENST00000932637',
 'ENST00000932638',
 'ENST00000932639',
 'ENST00000960479',
 'ENST00000960480',
 'ENST00000960481',
 'ENST00000960482',
 'ENST00000377263',
 'ENST00000851117',
 'ENST00000851118',
 'ENST00000851119',
 'ENST00000851120',
 'ENST00000851121',
 'ENST00000851122',
 'ENST00000851123',
 'ENST00000851124',
 'ENST00000851125',
 'ENST00000851126',
 'ENST00000851127',
 'ENST00000851128',
 'ENST00000851129',
 'ENST00000851130',
 'ENST00000851131',
 'ENST00000851132',
 'ENST00000851133',
 'ENST00000851144',
 'ENST00000851147',
 'ENST00000851148',
 'ENST00000851149',
 'ENST00000936601',
 'ENST00000936602',
 'ENST00000936603',
 'ENST00000936604',
 'ENST00000936605',
 'ENST00000936606',
 'ENST00000936607',
 'ENST00000936608',
 'ENST00000936609',
 'ENST00000936610',
 'ENST00000936613',
 'ENST00000955026',
 'ENST00000955029',
 'ENST00000955031',
 'ENST00000955035',
 'ENST00000955036',
 'ENST00000955037',
 'ENST00000400904',
 'ENST00000851134',
 'ENST00000851135',
 'ENST00000851136',
 'ENST00000851137',
 'ENST00000851138',
 'ENST00000851146',
 'ENST00000936611',
 'ENST00000936612',
 'ENST00000955032',
 'ENST00000955033',
 'ENST00000377223',
 'ENST00000867510',
 'ENST00000867511',
 'ENST00000937250',
 'ENST00000937251',
 'ENST00000377205',
 'ENST00000462686',
 'ENST00000887500',
 'ENST00000946962',
 'ENST00000946963',
 'ENST00000946964',
 'ENST00000946965',
 'ENST00000377093',
 'ENST00000696500',
 'ENST00000263934',
 'ENST00000377086',
 'ENST00000635499',
 'ENST00000676179',
 'ENST00000696502',
 'ENST00000696503',
 'ENST00000696504',
 'ENST00000858327',
 'ENST00000858328',
 'ENST00000858329',
 'ENST00000858330',
 'ENST00000858331',
 'ENST00000377081',
 'ENST00000620295',
 'ENST00000622724',
 'ENST00000270776',
 'ENST00000863228',
 'ENST00000922425',
 'ENST00000922426',
 'ENST00000922427',
 'ENST00000957131',
 'ENST00000309048',
 'ENST00000377038',
 'ENST00000942858',
 'ENST00000866602',
 'ENST00000377022',
 'ENST00000377004',
 'ENST00000418570',
 'ENST00000468348',
 'ENST00000240185',
 'ENST00000473869',
 'ENST00000913574',
 'ENST00000700089',
 'ENST00000700090',
 'ENST00000700091',
 'ENST00000700092',
 'ENST00000700093',
 'ENST00000700094',
 'ENST00000400897',
 'ENST00000700095',
 'ENST00000700096',
 'ENST00000860325',
 'ENST00000860326',
 'ENST00000860327',
 'ENST00000860328',
 'ENST00000860329',
 'ENST00000700097',
 'ENST00000376957',
 'ENST00000490101',
 'ENST00000882301',
 'ENST00000882302',
 'ENST00000923261',
 'ENST00000361445',
 'ENST00000703118',
 'ENST00000703139',
 'ENST00000703140',
 'ENST00000703141',
 'ENST00000703142',
 'ENST00000703143',
 'ENST00000875524',
 'ENST00000875525',
 'ENST00000934310',
 'ENST00000934311',
 'ENST00000934312',
 'ENST00000934313',
 'ENST00000934314',
 'ENST00000934315',
 'ENST00000376819',
 'ENST00000376810',
 'ENST00000294484',
 'ENST00000304391',
 'ENST00000922103',
 'ENST00000922104',
 'ENST00000922105',
 'ENST00000642025',
 'ENST00000717649',
 'ENST00000251546',
 'ENST00000251547',
 'ENST00000376762',
 'ENST00000376770',
 'ENST00000858192',
 'ENST00000858193',
 'ENST00000858194',
 'ENST00000858195',
 'ENST00000858196',
 'ENST00000858197',
 'ENST00000858198',
 'ENST00000858199',
 'ENST00000933204',
 'ENST00000933205',
 'ENST00000933206',
 'ENST00000933207',
 'ENST00000968217',
 'ENST00000968218',
 'ENST00000471895',
 'ENST00000475435',
 'ENST00000376753',
 'ENST00000907480',
 'ENST00000907481',
 'ENST00000907482',
 'ENST00000938498',
 'ENST00000961666',
 'ENST00000961667',
 'ENST00000294485',
 'ENST00000855916',
 'ENST00000911391',
 'ENST00000911392',
 'ENST00000911393',
 'ENST00000314340',
 'ENST00000376629',
 'ENST00000376637',
 'ENST00000510878',
 'ENST00000856549',
 'ENST00000856550',
 'ENST00000929521',
 'ENST00000376583',
 'ENST00000376585',
 'ENST00000376590',
 'ENST00000376592',
 'ENST00000911084',
 'ENST00000423400',
 'ENST00000641446',
 'ENST00000641747',
 'ENST00000911085',
 'ENST00000911086',
 'ENST00000970341',
 'ENST00000970342',
 'ENST00000970343',
 'ENST00000376572',
 'ENST00000923856',
 'ENST00000966533',
 'ENST00000376576',
 'ENST00000497302',
 'ENST00000675512',
 'ENST00000235329',
 'ENST00000444836',
 'ENST00000674548',
 'ENST00000674658',
 'ENST00000674817',
 'ENST00000674910',
 'ENST00000675053',
 'ENST00000675113',
 'ENST00000675231',
 'ENST00000675817',
 'ENST00000675919',
 'ENST00000675987',
 'ENST00000676293',
 'ENST00000676426',
 'ENST00000898883',
 'ENST00000898884',
 'ENST00000898885',
 'ENST00000898886',
 'ENST00000898887',
 'ENST00000898888',
 'ENST00000898889',
 'ENST00000898890',
 'ENST00000898891',
 'ENST00000898892',
 'ENST00000898893',
 'ENST00000898894',
 'ENST00000898895',
 'ENST00000898896',
 'ENST00000898897',
 'ENST00000898898',
 'ENST00000898899',
 'ENST00000898900',
 'ENST00000917332',
 'ENST00000967393',
 'ENST00000967394',
 'ENST00000967395',
 'ENST00000967396',
 'ENST00000967397',
 'ENST00000967398',
 'ENST00000967399',
 'ENST00000967400',
 'ENST00000967401',
 'ENST00000967402',
 'ENST00000967403',
 'ENST00000967404',
 'ENST00000967405',
 'ENST00000967406',
 'ENST00000967407',
 'ENST00000967408',
 'ENST00000967409',
 'ENST00000967410',
 'ENST00000967411',
 'ENST00000967412',
 'ENST00000967413',
 'ENST00000967414',
 'ENST00000967415',
 'ENST00000967416',
 'ENST00000967417',
 'ENST00000967418',
 'ENST00000967419',
 'ENST00000675298',
 'ENST00000376259',
 'ENST00000857300',
 'ENST00000857301',
 'ENST00000857302',
 'ENST00000857303',
 'ENST00000857304',
 'ENST00000941754',
 'ENST00000941755',
 'ENST00000941756',
 'ENST00000941757',
 'ENST00000941758',
 'ENST00000543766',
 'ENST00000613099',
 'ENST00000620676',
 'ENST00000616661',
 'ENST00000714541',
 'ENST00000714542',
 'ENST00000714544',
 'ENST00000714545',
 'ENST00000714546',
 'ENST00000875271',
 'ENST00000875272',
 'ENST00000946018',
 'ENST00000359318',
 'ENST00000614859',
 'ENST00000332296',
 'ENST00000619922',
 'ENST00000966578',
 'ENST00000376189',
 'ENST00000415464',
 'ENST00000415919',
 'ENST00000622421',
 'ENST00000334600',
 'ENST00000376098',
 'ENST00000376085',
 'ENST00000488631',
 'ENST00000294489',
 'ENST00000376057',
 'ENST00000376061',
 'ENST00000475043',
 'ENST00000513143',
 'ENST00000621990',
 'ENST00000921771',
 'ENST00000921772',
 'ENST00000921773',
 'ENST00000921774',
 'ENST00000235372',
 'ENST00000311066',
 'ENST00000376048',
 'ENST00000503842',
 'ENST00000505823',
 'ENST00000361144',
 'ENST00000400798',
 'ENST00000376030',
 'ENST00000636203',
 'ENST00000434578',
 'ENST00000376008',
 'ENST00000376014',
 'ENST00000400796',
 'ENST00000428417',
 'ENST00000887778',
 'ENST00000887779',
 'ENST00000887780',
 'ENST00000887781',
 'ENST00000926432',
 'ENST00000375997',
 'ENST00000444385',
 'ENST00000481324',
 'ENST00000314668',
 'ENST00000358897',
 'ENST00000375998',
 'ENST00000529606',
 'ENST00000683790',
 'ENST00000688493',
 'ENST00000940095',
 'ENST00000968213',
 'ENST00000375980',
 'ENST00000906256',
 'ENST00000906257',
 'ENST00000968587',
 'ENST00000375943',
 'ENST00000375949',
 'ENST00000375849',
 'ENST00000480945',
 'ENST00000711098',
 'ENST00000711099',
 'ENST00000718275',
 'ENST00000718276',
 'ENST00000850912',
 'ENST00000375793',
 'ENST00000375799',
 'ENST00000642363',
 'ENST00000850891',
 'ENST00000957353',
 'ENST00000957354',
 'ENST00000957355',
 'ENST00000957356',
 'ENST00000957357',
 'ENST00000375782',
 'ENST00000853368',
 'ENST00000441801',
 'ENST00000375766',
 'ENST00000375771',
 'ENST00000908346',
 'ENST00000908347',
 'ENST00000908348',
 'ENST00000908349',
 'ENST00000908350',
 'ENST00000908351',
 'ENST00000908352',
 'ENST00000908356',
 'ENST00000908357',
 'ENST00000908358',
 'ENST00000908359',
 'ENST00000908360',
 'ENST00000908361',
 'ENST00000908362',
 'ENST00000908363',
 'ENST00000908364',
 'ENST00000908365',
 'ENST00000908366',
 'ENST00000908367',
 'ENST00000908369',
 'ENST00000908370',
 'ENST00000915870',
 'ENST00000915871',
 'ENST00000915872',
 'ENST00000915873',
 'ENST00000915874',
 'ENST00000915875',
 'ENST00000915876',
 'ENST00000915877',
 'ENST00000915878',
 'ENST00000915879',
 'ENST00000915880',
 'ENST00000915883',
 'ENST00000915884',
 'ENST00000915885',
 'ENST00000944490',
 'ENST00000944493',
 'ENST00000944494',
 'ENST00000944495',
 'ENST00000944496',
 'ENST00000944498',
 'ENST00000438066',
 'ENST00000894622',
 'ENST00000329454',
 'ENST00000311890',
 'ENST00000375718',
 'ENST00000411503',
 'ENST00000861615',
 'ENST00000861616',
 'ENST00000956995',
 'ENST00000956996',
 'ENST00000956997',
 'ENST00000331433',
 'ENST00000375692',
 'ENST00000861477',
 'ENST00000861478',
 'ENST00000861479',
 'ENST00000861480',
 'ENST00000861481',
 'ENST00000861482',
 'ENST00000861483',
 'ENST00000861484',
 'ENST00000861485',
 'ENST00000861486',
 'ENST00000861487',
 'ENST00000861488',
 'ENST00000861489',
 'ENST00000861490',
 'ENST00000861491',
 'ENST00000861492',
 'ENST00000861493',
 'ENST00000861494',
 'ENST00000861495',
 'ENST00000861496',
 'ENST00000861497',
 'ENST00000861498',
 'ENST00000861499',
 'ENST00000861500',
 'ENST00000861501',
 'ENST00000861502',

In [18]:
with open('unique_transcripts.txt', 'w', encoding='utf-8') as f:
    f.write('\n'.join(map(str, transcripts)))

In [ ]:
num_files = 22
chunk_size = len(transcripts) // num_files

for i in range(num_files):
    start_idx = i * chunk_size
    end_idx = start_idx + chunk_size if i < num_files - 1 else len(transcripts)
    
    with open(f'trans{i+1}.txt', 'w', encoding='utf-8') as f:
        f.write('\n'.join(map(str, transcripts[start_idx:end_idx])))

In [5]:
import requests

transcriptsNum = 20

df2 = df.head(transcriptsNum)
downloadTranscripts = df2['Feature'].drop_duplicates().to_list()

url = "http://www.ensembl.org/biomart/martservice"
query_xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Query>
<Query  virtualSchemaName = "default" formatter = "FASTA" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" >
			
	<Dataset name = "hsapiens_gene_ensembl" interface = "default" >
		<Filter name = "ensembl_transcript_id" value = "{','.join(downloadTranscripts)}"/>
		<Attribute name = "ensembl_transcript_id" />
		<Attribute name = "cdna" />
	</Dataset>
</Query>"""

res = requests.get(url, params={"query": query_xml})
with open('./TarPmiR_Linux/cDNA.fasta', 'w') as file:
    file.write(res.text)

In [15]:
input_path = './output/miraw_mirna.fasta_miraw_mrna.fasta0.bp'
num_parts = 10

base, ext = input_path.rsplit('.', 1)
part_paths = [f'{base}_part{i+1}.{ext}' for i in range(num_parts)]

with open(input_path, 'w', encoding='utf-8') as f_out:
    for part_path in part_paths:
        with open(part_path, 'r', encoding='utf-8') as f_in:
            f_out.write(f_in.read())

In [14]:
import re
with open('output/miraw_mirna.fasta_miraw_mrna.fasta0_part10.bp', 'r', encoding='utf-8') as f_in:
    content = f_in.read()
content = re.sub(r'(?<=.)hsa', r'\nhsa', content)
content = re.sub(r'(?<=.)MIMAT', r'\nMIMAT', content)
with open('output/miraw_mirna.fasta_miraw_mrna.fasta0_part10.bp', 'w', encoding='utf-8') as f_out:
    f_out.write(content)

In [1]:

import re
from io import StringIO

with open('./TarPmiR_Linux/cDNA.fasta', 'r', encoding='utf-8') as f:
    fasta_ids = [line.strip()[1:] for line in f if line.startswith('>')]
    
with open('./TarPmiR_Linux/mirnatest.fasta_cDNA.fasta.bp', 'r', encoding='utf-8') as f_in:
    content = f_in.read()
content = re.sub(r'(?<=.)hsa', r'\nhsa', content)
with open('./TarPmiR_Linux/mirnatest.fasta_cDNA.fasta.bp', 'w', encoding='utf-8') as f_out:
    f_out.write(content)
dftarp = pd.read_csv(StringIO(content), sep='\t')

dftarp.columns = ['miRNA','mRNA','binding_site','binding_probability','energy','seed','accessibility','AU_content','PhyloP_Stem','PyloP_Flanking','m/e','number_of_pairings','binding_region_length','longest_consecutive_pairings','position_of_longest_consecutive_pairings','pairings_in_3prime_end','difference_of_pairings_between_seed_and_3prime_end']
dftarp.loc[:, 'miRNA'] = dftarp['miRNA'].str.split().str[0]
binds = dftarp.groupby('mRNA')['miRNA'].apply(lambda s: ';'.join(map(str, s))).to_dict()

df2.loc[:, 'hasSequence'] = df2['Feature'].isin(fasta_ids)
# df2.loc[:, 'miRNAHits'] = df2['Feature'].map(binds).where(df2['Feature'].map(binds).notna(), None)

# parse binding_site to numeric start/end
dftarp[['bs_start', 'bs_end']] = (
    dftarp['binding_site'].str.split(',', expand=True).astype(int)
)

df2

NameError: name 'pd' is not defined

In [7]:
dftarp

,miRNA,mRNA,binding_site,binding_probability,energy,seed,accessibility,AU_content,PhyloP_Stem,PyloP_Flanking,m/e,number_of_pairings,binding_region_length,longest_consecutive_pairings,position_of_longest_consecutive_pairings,pairings_in_3prime_end,difference_of_pairings_between_seed_and_3prime_end,bs_start,bs_end
0,hsa-miR-30c-2-3p,ENST00000870726,"2300,2323",0.692308,-21.7,0,4.511229e-09,0.250,0,0,-10.752244,18,23,7,8,8,3,2300,2323
1,hsa-miR-30c-2-3p,ENST00000870726,"814,851",0.153846,-20.2,0,9.222966e-07,0.368,0,0,-8.865139,17,37,7,10,6,0,814,851
2,hsa-miR-30d-5p,ENST00000870726,"2648,2668",0.923077,-19.7,0,1.191108e-07,0.294,0,0,-15.407181,15,20,11,9,6,2,2648,2668
3,hsa-miR-30d-5p,ENST00000870726,"2460,2475",0.461538,-19.1,0,8.027291e-04,0.441,0,0,-17.880193,12,15,10,3,5,4,2460,2475
4,hsa-miR-30d-5p,ENST00000870726,"45,83",0.307692,-16.7,0,3.768705e-08,0.294,0,0,-16.846914,16,38,6,7,7,4,45,83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1320,hsa-miR-218-1-3p,ENST00000870727,"499,522",0.538462,-22.7,0,2.554646e-05,0.441,0,0,-12.318121,17,23,7,16,8,2,499,522
1321,hsa-miR-218-2-3p,ENST00000870727,"2749,2770",1.000000,-29.3,1,3.553495e-05,0.500,0,0,-6.674745,17,21,11,1,6,1,2749,2770
1322,hsa-miR-218-2-3p,ENST00000870727,"1121,1144",1.000000,-25.1,1,1.516049e-04,0.382,0,0,-4.170624,19,23,13,4,5,3,1121,1144
1323,hsa-miR-219a-5p,ENST00000870727,"775,797",0.692308,-15.3,0,1.148641e-03,0.368,0,0,-10.762870,16,22,9,1,5,2,775,797
1324,hsa-miR-219a-5p,ENST00000870727,"2146,2168",0.461538,-15.3,0,1.145593e-02,0.368,0,0,-13.142247,15,22,8,1,6,1,2146,2168

In [7]:
df2

,Uploaded_variation,Location,Allele,Gene,Feature,Feature_type,Consequence,cDNA_position,CDS_position,Protein_position,Amino_acids,Codons,Existing_variation,Extra,hasSequence,miRNADisrupt
11793,chr1_71298_G/A,chr1:71298,A,ENSG00000186092,ENST00000641515,Transcript,3_prime_UTR_variant,2331,-,-,-,-,-,IMPACT=MODIFIER;STRAND=1,True,hsa-miR-224-5p;hsa-miR-3126-3p;hsa-miR-5586-3p
74226,rs56972694,chr1:943527-943529,-,ENSG00000188976,ENST00000870725,Transcript,3_prime_UTR_variant,3483-3485,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1,True,None
74292,rs6605067,chr1:944296,A,ENSG00000188976,ENST00000327044,Transcript,3_prime_UTR_variant,2664,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1,True,hsa-miR-205-3p;hsa-miR-6733-5p
74293,rs6605067,chr1:944296,A,ENSG00000187634,ENST00000341065,Transcript,3_prime_UTR_variant,1912,-,-,-,-,-,IMPACT=MODIFIER;STRAND=1;FLAGS=cds_start_NF,True,hsa-miR-152-5p;hsa-miR-301a-5p;hsa-miR-550a-3p...
74294,rs6605067,chr1:944296,A,ENSG00000187634,ENST00000342066,Transcript,3_prime_UTR_variant,2279,-,-,-,-,-,IMPACT=MODIFIER;STRAND=1,True,hsa-miR-152-5p;hsa-miR-550a-3p;hsa-miR-627-3p
74303,rs6605067,chr1:944296,A,ENSG00000187634,ENST00000616016,Transcript,3_prime_UTR_variant,3187,-,-,-,-,-,IMPACT=MODIFIER;STRAND=1,True,hsa-miR-152-5p;hsa-miR-550a-3p;hsa-miR-627-3p
74307,rs6605067,chr1:944296,A,ENSG00000187634,ENST00000618323,Transcript,3_prime_UTR_variant,3190,-,-,-,-,-,IMPACT=MODIFIER;STRAND=1,True,hsa-miR-152-5p;hsa-miR-550a-3p;hsa-miR-627-3p
74310,rs6605067,chr1:944296,A,ENSG00000188976,ENST00000870725,Transcript,3_prime_UTR_variant,2716,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1,True,hsa-miR-205-3p;hsa-miR-6733-5p
74311,rs6605067,chr1:944296,A,ENSG00000188976,ENST00000870726,Transcript,3_prime_UTR_variant,2768,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1,True,hsa-miR-205-3p;hsa-miR-6733-5p
74312,rs6605067,chr1:944296,A,ENSG00000188976,ENST00000870727,Transcript,3_prime_UTR_variant,2684,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1,True,hsa-miR-205-3p;hsa-miR-6733-5p
74313,rs6605067,chr1:944296,A,ENSG00000188976,ENST00000870728,Transcript,3_prime_UTR_variant,2695,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1,True,hsa-miR-205-3p;hsa-miR-6733-5p
74314,rs6605067,chr1:944296,A,ENSG00000188976,ENST00000870729,Transcript,3_prime_UTR_variant,2760,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1,True,hsa-miR-205-3p;hsa-miR-6733-5p
74315,rs6605067,chr1:944296,A,ENSG00000188976,ENST00000870730,Transcript,3_prime_UTR_variant,2673,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1,True,hsa-miR-205-3p;hsa-miR-6733-5p
74316,rs6605067,chr1:944296,A,ENSG00000188976,ENST00000870731,Transcript,3_prime_UTR_variant,2691,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1,True,hsa-miR-205-3p;hsa-miR-6733-5p
74317,rs6605067,chr1:944296,A,ENSG00000188976,ENST00000870732,Transcript,3_prime_UTR_variant,2598,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1,True,hsa-miR-205-3p;hsa-miR-6733-5p
74318,rs6605067,chr1:944296,A,ENSG00000188976,ENST00000870733,Transcript,3_prime_UTR_variant,2718,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1,True,hsa-miR-205-3p;hsa-miR-6733-5p
74319,rs6605067,chr1:944296,A,ENSG00000188976,ENST00000870734,Transcript,3_prime_UTR_variant,2733,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1,True,hsa-miR-205-3p;hsa-miR-6733-5p
74320,rs6605067,chr1:944296,A,ENSG00000188976,ENST00000870735,Transcript,3_prime_UTR_variant,2693,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1,True,hsa-miR-205-3p;hsa-miR-6733-5p
74321,rs6605067,chr1:944296,A,ENSG00000188976,ENST00000870736,Transcript,3_prime_UTR_variant,2511,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1,True,hsa-miR-205-3p;hsa-miR-6733-5p
74322,rs6605067,chr1:944296,A,ENSG00000188976,ENST00000870737,Transcript,3_prime_UTR_variant,2299,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1,True,hsa-miR-205-3p;hsa-miR-6733-5p

In [ ]:
def findDisrupted(row):
    pos = row['cDNA_position']
    local_dftarp = dftarp[dftarp['mRNA'] == row['Feature']]
    if local_dftarp.empty:
        return None

    if '-' in pos:
        pos1, pos2 = map(int, pos.split('-', 1))
    else:
        pos1 = pos2 = int(pos)

    hits = pd.concat([
        local_dftarp[
            (local_dftarp['bs_start'] <= pos_iter) &
            (local_dftarp['bs_end'] >= pos_iter)
        ]
        for pos_iter in range(pos1, pos2 + 1)
    ], ignore_index=True).drop_duplicates()
    
    if hits.empty:
        return None

    return ';'.join(sorted(hits['miRNA'].unique()))


df2.loc[:, 'miRNADisrupt'] = df2.apply(findDisrupted, axis=1)

/home/nikos/miniconda3/envs/TarPmiR/lib/python3.7/site-packages/pandas/core/indexing.py:1667: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = value

In [5]:
dftarp = dftarp[['miRNA', 'mRNA']].join(dftarp['binding_site'].str.split(',', expand=True).astype(int).rename(columns={0: 'bs_start', 1: 'bs_end'}))

dftarp

                 miRNA             mRNA  bs_start  bs_end
0        hsa-let-7a-5p  ENST00000341065      1033    1047
1        hsa-let-7a-5p  ENST00000341065       117     133
2        hsa-let-7a-3p  ENST00000341065       166     187
3      hsa-let-7a-2-3p  ENST00000341065      1378    1402
4      hsa-let-7a-2-3p  ENST00000341065      1933    1961
...                ...              ...       ...     ...
35049  hsa-miR-3059-3p  ENST00000870737      1956    1982
35050  hsa-miR-3085-5p  ENST00000870737       920     981
35051  hsa-miR-3085-3p  ENST00000870737      1924    1949
35052  hsa-miR-3085-3p  ENST00000870737      1829    1849
35053  hsa-miR-3085-3p  ENST00000870737       328     356

[35054 rows x 4 columns]

In [33]:
dftarp[dftarp['mRNA'] == 'ENST00000641515']

                miRNA             mRNA bs_start bs_end
0       hsa-let-7a-5p  ENST00000641515     1786   1811
1     hsa-let-7a-2-3p  ENST00000641515      646    674
2       hsa-let-7b-5p  ENST00000641515     1140   1188
3       hsa-let-7b-5p  ENST00000641515      274    301
4       hsa-let-7b-3p  ENST00000641515     2483   2524
...               ...              ...      ...    ...
1445  hsa-miR-3059-3p  ENST00000641515     1618   1636
1446  hsa-miR-3085-5p  ENST00000641515     1651   1707
1447  hsa-miR-3085-5p  ENST00000641515     1620   1648
1448  hsa-miR-3085-3p  ENST00000641515      547    580
1449  hsa-miR-3085-3p  ENST00000641515     2256   2278

[1450 rows x 4 columns]

In [17]:
df2[['Feature', 'cDNA_position', 'miRNADisrupt']]

,Feature,cDNA_position,miRNADisrupt
11793,ENST00000641515,2331,hsa-miR-224-5p;hsa-miR-3126-3p;hsa-miR-5586-3p
74226,ENST00000870725,3483-3485,None
74292,ENST00000327044,2664,hsa-miR-205-3p;hsa-miR-6733-5p
74293,ENST00000341065,1912,hsa-miR-152-5p;hsa-miR-301a-5p;hsa-miR-550a-3p...
74294,ENST00000342066,2279,hsa-miR-152-5p;hsa-miR-550a-3p;hsa-miR-627-3p

In [11]:
import requests
import re

transcriptsNum = 100

df2 = df.head(transcriptsNum)
downloadTranscripts = df2['Feature'].drop_duplicates().to_list()

url = "http://www.ensembl.org/biomart/martservice"
query_xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Query>
<Query  virtualSchemaName = "default" formatter = "FASTA" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" >
			
	<Dataset name = "hsapiens_gene_ensembl" interface = "default" >
		<Filter name = "ensembl_transcript_id" value = "{','.join(downloadTranscripts)}"/>
		<Attribute name = "ensembl_transcript_id" />
		<Attribute name = "cdna" />
	</Dataset>
</Query>"""

res = requests.get(url, params={"query": query_xml})
with open('./TarPmiR_Linux/cDNA.fasta', 'w') as file:
    file.write(res.text)
    
with open('./TarPmiR_Linux/cDNA.fasta', 'r', encoding='utf-8') as f:
    fasta_ids = [line.strip()[1:] for line in f if line.startswith('>')]
    
testTarPmiR()
    
with open('./TarPmiR_Linux/mirnaverified.fasta_cDNA.fasta.bp', 'r', encoding='utf-8') as f_in:
    content = f_in.read()

content = re.sub(r'(?<=.)hsa', r'\nhsa', content)

with open('./TarPmiR_Linux/mirnaverified.fasta_cDNA.fasta.bp', 'w', encoding='utf-8') as f_out:
    f_out.write(content)
dftarp = pd.read_csv(
    './TarPmiR_Linux/mirnaverified.fasta_cDNA.fasta.bp',
    sep='\t'
)
dftarp.columns = ['miRNA','mRNA','binding_site','binding_probability','energy','seed','accessibility','AU_content','PhyloP_Stem','PyloP_Flanking','m/e','number_of_pairings','binding_region_length','longest_consecutive_pairings','position_of_longest_consecutive_pairings','pairings_in_3prime_end','difference_of_pairings_between_seed_and_3prime_end']
dftarp.loc[:, 'miRNA'] = dftarp['miRNA'].str.split().str[0]
binds = dftarp.groupby('mRNA')['miRNA'].apply(lambda s: ';'.join(map(str, s))).to_dict()

df2.loc[:, 'hasSequence'] = df2['Feature'].isin(fasta_ids)
df2.loc[:, 'miRNAHits'] = df2['Feature'].map(binds).where(df2['Feature'].map(binds).notna(), None)

df2

/home/nikos/miniconda3/envs/TarPmiR/lib/python3.7/site-packages/pandas/core/indexing.py:1667: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = value

,Uploaded_variation,Location,Allele,Gene,Feature,Feature_type,Consequence,cDNA_position,CDS_position,Protein_position,Amino_acids,Codons,Existing_variation,Extra,hasSequence,miRNAHits
11793,chr1_71298_G/A,chr1:71298,A,ENSG00000186092,ENST00000641515,Transcript,3_prime_UTR_variant,2331,-,-,-,-,-,IMPACT=MODIFIER;STRAND=1,True,hsa-let-7a-5p;hsa-let-7b-5p;hsa-let-7c-5p;hsa-...
74226,rs56972694,chr1:943527-943529,-,ENSG00000188976,ENST00000870725,Transcript,3_prime_UTR_variant,3483-3485,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1,True,hsa-let-7b-5p;hsa-let-7c-5p;hsa-miR-15a-5p;hsa...
74292,rs6605067,chr1:944296,A,ENSG00000188976,ENST00000327044,Transcript,3_prime_UTR_variant,2664,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1,True,hsa-let-7a-5p;hsa-let-7a-2-3p;hsa-let-7b-5p;hs...
74293,rs6605067,chr1:944296,A,ENSG00000187634,ENST00000341065,Transcript,3_prime_UTR_variant,1912,-,-,-,-,-,IMPACT=MODIFIER;STRAND=1;FLAGS=cds_start_NF,True,hsa-let-7a-5p;hsa-let-7b-5p;hsa-let-7c-5p;hsa-...
74294,rs6605067,chr1:944296,A,ENSG00000187634,ENST00000342066,Transcript,3_prime_UTR_variant,2279,-,-,-,-,-,IMPACT=MODIFIER;STRAND=1,True,hsa-let-7e-3p;hsa-miR-17-3p;hsa-miR-18a-5p;hsa...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74411,rs2839,chr1:944307,C,ENSG00000188976,ENST00000934934,Transcript,3_prime_UTR_variant,2695,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1,True,hsa-let-7a-2-3p;hsa-let-7e-3p;hsa-miR-15a-5p;h...
74412,rs2839,chr1:944307,C,ENSG00000188976,ENST00000934935,Transcript,3_prime_UTR_variant,2634,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1,True,hsa-let-7a-2-3p;hsa-let-7e-3p;hsa-miR-15a-5p;h...
74413,rs2839,chr1:944307,C,ENSG00000188976,ENST00000934936,Transcript,3_prime_UTR_variant,2424,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1,True,hsa-let-7a-2-3p;hsa-let-7e-3p;hsa-miR-15a-5p;h...
74414,rs2839,chr1:944307,C,ENSG00000188976,ENST00000934937,Transcript,3_prime_UTR_variant,2684,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1,True,hsa-let-7a-2-3p;hsa-let-7b-5p;hsa-let-7e-3p;hs...
74415,rs2839,chr1:944307,C,ENSG00000188976,ENST00000934938,Transcript,3_prime_UTR_variant,2578,-,-,-,-,-,IMPACT=MODIFIER;STRAND=-1,True,hsa-let-7a-2-3p;hsa-let-7e-3p;hsa-let-7f-2-3p;...

## ~~Kano requests sto Ensembl me ta transcript ids tou gia na vro ta NM_ id pou einai referenced~~
[Ensembl REST API](https://rest.ensembl.org/)

[API CrossRef GET Request](https://rest.ensembl.org/documentation/info/xref_id)

In [ ]:
import requests

In [ ]:
transcriptid ='ENST00000327044'
res = requests.get(f'https://rest.ensembl.org/xrefs/id/{transcriptid}?external_db=RefSeq_mRNA', headers={"content-type":"application/json"})

res.json()

### Get request - pairnei peripou 0,29 defterolepta gia kathe id (an kano olo to output me 33000 ids tha parei peripou 3 ores)

In [ ]:
dict = {}
for id in transcripts:
    print("Getting " + id)
    res = requests.get(f'https://rest.ensembl.org/xrefs/id/{id}?external_db=RefSeq_mRNA', headers={"content-type":"application/json"}).json()
    if res == []:
        dict[id] = None
        continue
    dict[id] = res[0]['primary_id']
    
dict

### Post request - den fainetai na mporo na paro to NM_ apo ta post requests pou mporo na kano

In [ ]:
idList = ['ENST00000327044', 'ENST00000379370']
server = "https://rest.ensembl.org"
ext = "/lookup/id"
headers={ "Content-Type" : "application/json", "Accept" : "application/json"}
r = requests.post('https://rest.ensembl.org/lookup/id', headers=headers, data='{"ids":["ENST00000327044","ENST00000379370"]}')

r.json()

## TarPmiR test

In [17]:
idList = transcripts[10:15]
res = ''
for transcriptid in idList:
    res += requests.get(f'https://rest.ensembl.org/sequence/id/{transcriptid}?type=cdna', headers={"content-type":"text/x-fasta"}).text

res

'>ENST00000870729.1\nGGGGCCGGAAGTGGGGTGCACGCTTCGGGTTGGTGTCATGGCAGCTGCGGGGAGCCGCAA\nGAGGCGCCTGGCGGAGCTGACGGTGGACGAGTTCCTAGCTTCGGGCTTTGACTCCGAGTC\nCGAATCCGAGTCCGAAAATTCTCCACAAGCGGAGACACGGGAAGCACGCGAGGCTGCCCG\nGAGTCCGGATAAGCCGGGCGGGAGCCCCTCGGCCAGCCGGCGTAAAGGCCGTGCCTCTGA\nGCACAAAGACCAGCTCTCTCGGCTGAAGGACAGAGACCCCGAGTTCTACAAGTTCCTGCA\nGGAGAATGACCAGAGCCTGCTAAACTTCAGCGACTCGGACAGCTCTGAGGAGGAAGAGGG\nGCCGTTCCACTCCCTGCCAGATGTGCTGGAGGAAGCCAGTGAGGAGGAGGATGGAGCGGA\nGGAAGGAGAAGATGGGGACAGAGTCCCCAGAGGGCTGAAGGGGAAGAAGAATTCTGTTCC\nTGTGACCGTCGCCATGGTTGAGAGATGGAAGCAGGCAGCAAAGCAACGCCTCACTCCAAA\nGCTGTTCCATGAAGTGGTACAGGCGTTCCGAGCAGCTGTGGCCACCACCCGAGGGGACCA\nGGAAAGTGCTGAGGCCAACAAATTCCAGGTCACGGACAGTGCTGCATTCAATGCTCTGGT\nTACCTTCTGCATCAGAGACCTCATTGGCTGTCTCCAGAAGCTGCTGTTTGGAAAGGTGGC\nAAAGGATAGCAGCAGCAAATGTGGGCCAAAGGAAACCAGTCTGCGGCAGTTGGTGGTGCC\nTGGGCGACCCCAGAGGATGCTGCAGCCGTCCAGCAGCCCGCTCTGGGGGAAGCTTCGTGT\nGGACATCAAGGCTTACCTGGGCTCGGCCATACAGCTGGTGTCCTGTCTGTCGGAGACGAC\nGGTGTTGGCGGCCGTGCTGCGGCACATCAGCGTGCTGGTGCCCTGCTTCCTGACCTTCCC\nCAAGCAGTGCCGCATGCTGCTCAAGAGAATGGTGATCGTATGGAGCACTGGGGAAGAGTC\nTCTGCGGGTGCTGGCTTTCCTGGTCCTCAGCAGAGTCTGCCGGCACAAGAAGGACACTTT\nCCTTGGCCCCGTCCTCAAGCAAATGTACATCACGTATGTGAGGAACTGCAAGTTCACCTC\nGCCTGGTGCCCTCCCCTTCATCAGTTTCATGCAGTGGACCTTGACGGAGCTGCTGGCCCT\nGGAGCCGGGTGTGGCCTACCAGCACGCCTTCCTCTACATCCGCCAGCTCGCCATACACCT\nGCGCAACGCCATGACCACTCGCAAGAAGGAAACATACCAGTCTGTGTACAACTGGCAGTA\nTGTGCACTGCCTCTTCCTGTGGTGCCGGGTCCTGAGCACTGCGGGCCCCAGCGAAGCCCT\nCCAGCCCTTGGTCTACCCCCTTGCCCAAGTCATCATTGGCTGTATCAAGCTCATCCCCAC\nTGCCCGCTTCTACCCGCTGCGAATGCACTGCATCCGTGCCCTGACGCTGCTCTCGGGGAG\nCTCGGGGGCCTTCATCCCGGTGCTGCCTTTCATCCTGGAGATGTTCCAGCAGGTCGACTT\nCAACAGGAAGCCAGGGCGCATGAGCTCCAAGCCCATCAACTTCTCCGTGATCCTGAAGCT\nGTCCAATGTCAACCTGCAGGAGAAGGCGTACCGGGACGGCCTGGTGGAGCAGCTGTACGA\nCCTCACCCTGGAGTACCTGCACAGCCAGGCACACTGCATCGGCTTCCCGGAGCTGGTGCT\nGCCTGTGGTCCTGCAGCTGAAGTCGTTCCTCCGGGAGTGCAAGGTGGCCAACTACTGCCG\nGCAGGTGCAGCAGCTGCTTGGGAAGGTTCAGGAGAACTCGGCATACATCTGCAGCCGCCG\nCCAGAGGGTTTCCTTCGGCGTCTCTGAGCAGCAGGCAGTGGAAGCCTGGGAGAAGCTGAC\nCCGGGAAGAGGGGACACCCCTGACCTTGTACTACAGCCACTGGCGCAAGCTGCGTGACCG\nGGAGATCCAGCTGGAGATCAGTGGCAAAGAGCGGCTGGAAGACCTGAACTTCCCTGAGAT\nCAAACGAAGGAAGATGGCTGACAGGAAGGATGAGGACAGGAAGCAATTTAAAGACCTCTT\nTGACCTGAACAGCTCTGAAGAGGACGACACCGAGGGATTCTCGGAGAGAGGGATACTGAG\nGCCCCTGAGCACTCGGCATGGGGTGGAAGACGATGAAGAGGACGAGGAGGAGGGCGAGGA\nGGACAGCAGCAACTCGGAGGGTGAATGGTCTTGGGATGGAGACCCAGACGCAGAGGCGGG\nGCTGGCCCCTGGGGAGCTGCAGCAGCTGGCCCAGGGGCCGGAGGACGAGCTGGAGGATCT\nGCAGCTCTCAGAGGACGACTGAGGCAGCCCATCTGGGGGGCCTGTAGGGGCTGCCGGGCT\nGGTGGCCAGTGTTTCCACCTCCCTGGCAGTCAGGCCTAGAGGCTGGCGTCTGTGCAGTTG\nGGGGAGGCAGTAGACACGGGACAGGCTTTATTATTTATTTTTCAGCATGAAAGACCAAAC\nGTATCGAGAGCTGGGCTGGGCTGGGCTGGTGTGGCTGCTGAAGCCCCACAGCTGTGGGCT\nGCTGAAGTCAGCTCCGCGGGGGAGCTGACCCTGACGTCAGCAGACCGAGACCAGTCCCAG\nTTCCAGGGGGAGGCCTGCAGGCCCCTGGCCCCTTCCACCACCTCTGCCCTCCGTCTGCAG\nACCTCGTCCATCTGCACCAGGCTCTGCCTTCACTCCCCCAAGTCTTTGAAAATTTGTTCC\nTTTCCTTTGAAGTCACATTTTCTTTTAAAATTTTTTGTTTTGCATCCGAAACCGAAAGAA\nATAAAGCGGTGGGAGGCAGGGCCATTGTGTTGA\n>ENST00000870730.1\nGGGGCCGGAAGTGGGGTGCACGCTTCGGGTTGGTGTCATGGCAGCTGCGGGGAGCCGCAA\nGAGGCGCCTGGCGGAGCTGACGGTGGACGAGTTCCTAGCTTCGGGCTTTGACTCCGAGTC\nCGAATCCGAGTCCGAAAATTCTCCACAAGCGGAGACACGGGAAGCACGCGAGGCTGCCCG\nGAGTCCGGATAAGCCGGGCGGGAGCCCCTCGGCCAGCCGGCGTAAAGGCCGTGCCTCTGA\nGCACAAAGACCAGCTCTCTCGGCTGAAGGACAGAGACCCCGAGTTCTACAAGTTCCTGCA\nGGAGAATGACCAGAGCCTGCTAAACTTCAGCGACTCGGACAGCTCTGAGGAGGAAGAGGG\nGCCGTTCCACTCCCTGCCAGATGTGCTGGAGGAAGCCAGTGAGGAGGAGGATGGAGCGGA\nGGAAGGAGAAGATGGGGACAGAGTCCCCAGAGGGCTGAAGGGGAAGAAGAATTCTGTTCC\nTGTGACCGTCGCCATGGTTGAGAGATGGAAGCAGGCAGCAAAGCAACGCCTCACTCCAAA\nGCTGTTCCATGAAGTGGTACAGGCGTTCCGAGCAGCTGTGGCCACCACCCGAGGGGACCA\nGGAAAGTGCTGAGGCCAACAAATTCCAGGTCACGGACAGTGCTGCATTCAATGCTCTGGT\nTACCTTCTGCATCAGAGACCTCATTGGCTGTCTCCAGAAGCTGCTGTTTGGAAAGGTGGC\nAAAGGATAGCAGCAGGATGCTGCAGCCGTCCAGCAGCCCGCTCTGGGGGAAGCTTCGTGT\nGGACATCAAGGCTTACCTGGGCTCGGCCATACAGCTGGTGTCCTGTCTGTCGGAGACGAC\nGGTGTTGGCGGCCGTGCTGCGGCACATCAGCGTGCTGGTGCCCTGCTTCCTGACCTTCCC\nCAAGCAGTGCCGCATGCTGCTCAAGAGAATGGTGATCGTATGGAGCACTGGGGAAGAGTC\nTCTGCGGGTGCTGGCTTTCCTGGTCCTCAGCAGAGTCTGCCGGCACAAGAAGGACACTTT\nCCTTGGCCCCGTCCTCAAGCAAATGTACATCACGTATGTGAGGAACTGCAAGTTCACCTC\nGCCTGGTGCCCTCCCCTTCATCAGTTTCATGCAGTGGACCTTGACGGAGCTGCTGGCCCT\nGGAGCCGGGTGTGGCCTACCAGCACGCCTTCCTCTACATCCGCCAGCTCGCCATACACCT\nGCGCAACGCCATGACCACTCGCAAGAAGGAAACATACCAGTCTGTGTACAACTGGCAGTA\nTGTGCACTGCCTCTTCCTGTGGTGCCGGGTCCTGAGCACTGCGGGCCCCAGCGAAGCCCT\nCCAGCCCTTGGTCTACCCCCTTGCCCAAGTCATCATTGGCTGTATCAAGCTCATCCCCAC\nTGCCCGCTTCTACCCGCTGCGAATGCACTGCATCCGTGCCCTGACGCTGCTCTCGGGGAG\nCTCGGGGGCCTTCATCCCGGTGCTGCCTTTCATCCTGGAGGTCGACTTCAACAGGAAGCC\nAGGGCGCATGAGCTCCAAGCCCATCAACTTCTCCGTGATCCTGAAGCTGTCCAATGTCAA\nCCTGCAGGAGAAGGCGTACCGGGACGGCCTGGTGGAGCAGCTGTACGACCTCACCCTGGA\nGTACCTGCACAGCCAGGCACACTGCATCGGCTTCCCGGAGCTGGTGCTGCCTGTGGTCCT\nGCAGCTGAAGTCGTTCCTCCGGGAGTGCAAGGTGGCCAACTACTGCCGGCAGGTGCAGCA\nGCTGCTTGGGAAGGTTCAGGAGAACTCGGCATACATCTGCAGCCGCCGCCAGAGGGTTTC\nCTTCGGCGTCTCTGAGCAGCAGGCAGTGGAAGCCTGGGAGAAGCTGACCCGGGAAGAGGG\nGACACCCCTGACCTTGTACTACAGCCACTGGCGCAAGCTGCGTGACCGGGAGATCCAGCT\nGGAGATCAGTGGCAAAGAGCGGCTGGAAGACCTGAACTTCCCTGAGATCAAACGAAGGAA\nGATGGCTGACAGGAAGGATGAGGACAGGAAGCAATTTAAAGACCTCTTTGACCTGAACAG\nCTCTGAAGAGGACGACACCGAGGGATTCTCGGAGAGAGGGATACTGAGGCCCCTGAGCAC\nTCGGCATGGGGTGGAAGACGATGAAGAGGACGAGGAGGAGGGCGAGGAGGACAGCAGCAA\nCTCGGAGGATGGAGACCCAGACGCAGAGGCGGGGCTGGCCCCTGGGGAGCTGCAGCAGCT\nGGCCCAGGGGCCGGAGGACGAGCTGGAGGATCTGCAGCTCTCAGAGGACGACTGAGGCAG\nCCCATCTGGGGGGCCTGTAGGGGCTGCCGGGCTGGTGGCCAGTGTTTCCACCTCCCTGGC\nAGTCAGGCCTAGAGGCTGGCGTCTGTGCAGTTGGGGGAGGCAGTAGACACGGGACAGGCT\nTTATTATTTATTTTTCAGCATGAAAGACCAAACGTATCGAGAGCTGGGCTGGGCTGGGCT\nGGTGTGGCTGCTGAAGCCCCACAGCTGTGGGCTGCTGAAGTCAGCTCCGCGGGGGAGCTG\nACCCTGACGTCAGCAGACCGAGACCAGTCCCAGTTCCAGGGGGAGGCCTGCAGGCCCCTG\nGCCCCTTCCACCACCTCTGCCCTCCGTCTGCAGACCTCGTCCATCTGCACCAGGCTCTGC\nCTTCACTCCCCCAAGTCTTTGAAAATTTGTTCCTTTCCTTTGAAGTCACATTTTCTTTTA\nAAATTTTTTGTTTTGCATCCGAAACCGAAAGAAATAAAGCGGTGGGAGGCAGGGCCATTG\nTGTTGA\n>ENST00000870731.1\nGGGGCCGGAAGTGGGGTGCACGCTTCGGGTTGGTGTCATGGCAGCTGCGGGGAGCCGCAA\nGAGGCGCCTGGCGGAGCTGACGGTGGACGAGTTCCTAGCTTCGGGCTTTGACTCCGAGTC\nCGAATCCGAGTCCGAAAATTCTCCACAAGCGGAGACACGGGAAGCACGCGAGGCTGCCCG\nGAGTCCGGATAAGCCGGGCGGGAGCCCCTCGGCCAGCCGGCGTAAAGGCCGTGCCTCTGA\nGCACAAAGACCAGCTCTCTCGGCTGAAGGACAGAGACCCCGAGTTCTACAAGTTCCTGCA\nGGAGAATGACCAGAGCCTGCTAAACTTCAGCGACTCGGACAGCTCTGAGGAGGAAGAGGG\nGCCGTTCCACTCCCTGCCAGATGTGCTGGAGGAAGCCAGTGAGGAGGAGGATGGAGCGGA\nGGAAGGAGAAGATGGGGACAGAGTCCCCAGAGGGCTGAAGGGGAAGAAGAATTCTGTTCC\nTGTGACCGTCGCCATGGTTGAGAGATGGAAGCAGGCAGCAAAGCAACGCCTCACTCCAAA\nGCTGTTCCATGAAGTGGTACAGGCGTTCCGAGCAGCTGTGGCCACCACCCGAGGGGACCA\nGGAAAGTGCTGAGGCCAACAAATTCCAGGTCACGGACAGTGCTGCATTCAATGCTCTGGT\nTACCTTCTGCATCAGAGACCTCATTGGCTGTCTCCAGAAGCTGCTGTTTGGAAAGGTGGC\nAAAGGATAGCAGCAGGATGCTGCAGCCGTCCAGCAGCCCGCTCTGGGGGAAGCTTCGTGT\nGGACATCAAGGCTTACCTGGGCTCGGCCATACAGCTGGTGTCCTGTCTGTCGGAGACGAC\nGGTGTTGGCGGCCGTGCTGCGGCACATCAGCGTGCTGGTGCCCTGCTTCCTGACCTTCCC\nCAAGCAGTGCCGCATGCTGCTCAAGAGAATGGTGATCGTATGGAGCACTGGGGAAGAGTC\nTCTGCGGGTGCTGGCTTTCCTGGTCCTCAGCAGAGTCTGCCGGCACAAGAAGGACACTTT\nCCTTGGCCCCGTCCTCAAGCAAATGTACATCACGTATGTGAGGAACTGCAAGTTCACCTC\nGCCTGGTGCCCTCCCCTTCATCAGTTTCATGCAGTGGACCTTGACGGAGCTGCTGGCCCT\nGGAGCCGGGTGTGGCCTACCAGCACGCCTTCCTCTACATCCGCCAGCTCGCCATACACCT\nGCGCAACGCCATGACCACTCGCAAGAAGGAAACATACCAGTCTGTGTACAACTGGCAGTA\nTGTGCACTGCCTCTTCCTGTGGTGCCGGGTCCTGAGCACTGCGGGCCCCAGCGAAGCCCT\nCCAGCCCTTGGTCTACCCCCTTGCCCAAGTCATCATTGGCTGTATCAAGCTCATCCCCAC\nTGCCCGCTTCTACCCGCTGCGAATGCACTGCATCCGTGCCCTGACGCTGCTCTCGGGGAG\nCTCGGGGGCCTTCATCCCGGTGCTGCCTTTCATCCTGGAGCAGGTCGACTTCAACAGGAA\nGCCAGGGCGCATGAGCTCCAAGCCCATCAACTTCTCCGTGATCCTGAAGCTGTCCAATGT\nCAACCTGCAGGAGAAGGCGTACCGGGACGGCCTGGTGGAGCAGCTGTACGACCTCACCCT\nGGAGTACCTGCACAGCCAGGCACACTGCATCGGCTTCCCGGAGCTGGTGCTGCCTGTGGT\nCCTGCAGCTGAAGTCGTTCCTCCGGGAGTGCAAGGTGGCCAACTACTGCCGGCAGGTGCA\nGCAGCTGCTTGGGAAGGTTCAGGAGAACTCGGCATACATCTGCAGCCGCCGCCAGAGGGT\nTTCCTTCGGCGTCTCTGAGCAGCAGGCAGTGGAAGCCTGGGAGAAGCTGACCCGGGAAGA\nGGGGACACCCCTGACCTTGTACTACAGCCACTGGCGCAAGCTGCGTGACCGGGAGATCCA\nGCTGGAGATCAGTGGCAAAGAGCGGCTGGAAGACCTGAACTTCCCTGAGATCAAACGAAG\nGAAGATGGCTGACAGGAAGGATGAGGACAGGAAGCAATTTAAAGACCTCTTTGACCTGAA\nCAGCTCTGAAGAGGACGACACCGAGGGATTCTCGGAGAGAGGGATACTGAGGCCCCTGAG\nCACTCGGCATGGGGTGGAAGACGATGAAGAGGACGAGGAGGAGGGCGAGGAGGACAGCAG\nCAACTCGGAGGGTGAATGGTCTTGGGATGGAGACCCAGACGCAGAGGCGGGGCTGGCCCC\nTGGGGAGCTGCAGCAGCTGGCCCAGGGGCCGGAGGACGAGCTGGAGGATCTGCAGCTCTC\nAGAGGACGACTGAGGCAGCCCATCTGGGGGGCCTGTAGGGGCTGCCGGGCTGGTGGCCAG\nTGTTTCCACCTCCCTGGCAGTCAGGCCTAGAGGCTGGCGTCTGTGCAGTTGGGGGAGGCA\nGTAGACACGGGACAGGCTTTATTATTTATTTTTCAGCATGAAAGACCAAACGTATCGAGA\nGCTGGGCTGGGCTGGGCTGGTGTGGCTGCTGAAGCCCCACAGCTGTGGGCTGCTGAAGTC\nAGCTCCGCGGGGGAGCTGACCCTGACGTCAGCAGACCGAGACCAGTCCCAGTTCCAGGGG\nGAGGCCTGCAGGCCCCTGGCCCCTTCCACCACCTCTGCCCTCCGTCTGCAGACCTCGTCC\nATCTGCACCAGGCTCTGCCTTCACTCCCCCAAGTCTTTGAAAATTTGTTCCTTTCCTTTG\nAAGTCACATTTTCTTTTAAAATTTTTTGTTTTGCATCCGAAACCGAAAGAAATAAAGCGG\nTGGGAGGCAGGGCCATTGTGTTG\n>ENST00000870732.1\nGGGGCCGGAAGTGGGGTGCACGCTTCGGGTTGGTGTCATGGCAGCTGCGGGGAGCCGCAA\nGAGGCGCCTGGCGGAGCTGACGGTGGACGAGTTCCTAGCTTCGGGCTTTGACTCCGAGTC\nCGAATCCGAGTCCGAAAATTCTCCACAAGCGGAGACACGGGAAGCACGCGAGGCTGCCCG\nGAGTCCGGATAAGCCGGGCGGGAGCCCCTCGGCCAGCCGGCGTAAAGGCCGTGCCTCTGA\nGCACAAAGACCAGCTCTCTCGGCTGAAGGACAGAGACCCCGAGTTCTACAAGTTCCTGCA\nGGAGAATGACCAGAGCCTGCTAAACTTCAGCGACTCGGACAGCTCTGAGGAGGAAGAGGG\nGCCGTTCCACTCCCTGCCAGATGTGCTGGAGGAAGCCAGTGAGGAGGAGGATGGAGCGGA\nGGAAGGAGAAGATGGGGACAGAGTCCCCAGAGGGCTGAAGGGGAAGAAGAATTCTGTTCC\nTGTGACCGTCGCCATGGTTGAGAGATGGAAGCAGGCAGCAAAGCAACGCCTCACTCCAAA\nGCTGTTCCATGAAGTGGTACAGGCGTTCCGAGCAGCTGTGGCCACCACCCGAGGGGACCA\nGGAAAGTGCTGAGGCCAACAAATTCCAGGTCACGGACAGTGCTGCATTCAATGCTCTGGT\nTACCTTCTGCATCAGAGACCTCATTGGCTGTCTCCAGAAGCTGCTGTTTGGAAAGGTGGC\nAAAGGATAGCAGCAGGATGCTGCAGCCGTCCAGCAGCCCGCTCTGGGGGAAGCTTCGTGT\nGGACATCAAGGCTTACCTGGGCTCGGCCATACAGCTGGTGTCCTGTCTGTCGGAGACGAC\nGGTGTTGGCGGCCGTGCTGCGGCACATCAGCGTGCTGGTGCCCTGCTTCCTGACCTTCCC\nCAAGCAGTGCCGCATGCTGCTCAAGAGAATGGTGATCGTATGGAGCACTGGGGAAGAGTC\nTCTGCGGGTGCTGGCTTTCCTGGTCCTCAGCAGAGTCTGCCGGCACAAGAAGGACACTTT\nCCTTGGCCCCGTCCTCAAGCAAATGTACATCACGTATGTGAGGAACTGCAAGTTCACCTC\nGCCTGGTGCCCTCCCCTTCATCAGTTTCATGCAGTGGACCTTGACGGAGCTGCTGGCCCT\nGGAGCCGGGTGTGGCCTACCAGCACGCCTTCCTCTACATCCGCCAGCTCGCCATACACCT\nGCGCAACGCCATGACCACTCGCAAGAAGGAAACATACCAGTCTGTGTACAACTGGCAGTA\nTGTGCACTGCCTCTTCCTGTGGTGCCGGGTCCTGAGCACTGCGGGCCCCAGCGAAGCCCT\nCCAGCCCTTGGTCTACCCCCTTGCCCAAGTCATCATTGGCTGTATCAAGCTCATCCCCAC\nTGCCCGCTTCTACCCGCTGCGAATGCACTGCATCCGTGCCCTGACGCTGCTCTCGGGGAG\nCTCGGGGGCCTTCATCCCGGTGCTGCCTTTCATCCTGGAGATGTTCCAGCAGGTCGACTT\nCAACAGGAAGCCAGGGCGCATGAGCTCCAAGCCCATCAACTTCTCCGTGATCCTGAAGCT\nGTCCAATGTCAACCTGCAGGAGAAGGCGTACCGGCTGAAGTCGTTCCTCCGGGAGTGCAA\nGGTGGCCAACTACTGCCGGCAGGTGCAGCAGCTGCTTGGGAAGGTTCAGGAGAACTCGGC\nATACATCTGCAGCCGCCGCCAGAGGGTTTCCTTCGGCGTCTCTGAGCAGCAGGCAGTGGA\nAGCCTGGGAGAAGCTGACCCGGGAAGAGGGGACACCCCTGACCTTGTACTACAGCCACTG\nGCGCAAGCTGCGTGACCGGGAGATCCAGCTGGAGATCAGTGGCAAAGAGCGGCTGGAAGA\nCCTGAACTTCCCTGAGATCAAACGAAGGAAGATGGCTGACAGGAAGGATGAGGACAGGAA\nGCAATTTAAAGACCTCTTTGACCTGAACAGCTCTGAAGAGGACGACACCGAGGGATTCTC\nGGAGAGAGGGATACTGAGGCCCCTGAGCACTCGGCATGGGGTGGAAGACGATGAAGAGGA\nCGAGGAGGAGGGCGAGGAGGACAGCAGCAACTCGGAGGGTGAATGGTCTTGGGATGGAGA\nCCCAGACGCAGAGGCGGGGCTGGCCCCTGGGGAGCTGCAGCAGCTGGCCCAGGGGCCGGA\nGGACGAGCTGGAGGATCTGCAGCTCTCAGAGGACGACTGAGGCAGCCCATCTGGGGGGCC\nTGTAGGGGCTGCCGGGCTGGTGGCCAGTGTTTCCACCTCCCTGGCAGTCAGGCCTAGAGG\nCTGGCGTCTGTGCAGTTGGGGGAGGCAGTAGACACGGGACAGGCTTTATTATTTATTTTT\nCAGCATGAAAGACCAAACGTATCGAGAGCTGGGCTGGGCTGGGCTGGTGTGGCTGCTGAA\nGCCCCACAGCTGTGGGCTGCTGAAGTCAGCTCCGCGGGGGAGCTGACCCTGACGTCAGCA\nGACCGAGACCAGTCCCAGTTCCAGGGGGAGGCCTGCAGGCCCCTGGCCCCTTCCACCACC\nTCTGCCCTCCGTCTGCAGACCTCGTCCATCTGCACCAGGCTCTGCCTTCACTCCCCCAAG\nTCTTTGAAAATTTGTTCCTTTCCTTTGAAGTCACATTTTCTTTTAAAATTTTTTGTTTTG\nCATCCGAAACCGAAAGAAATAAAGCGGTGGGAGGCAGGGCCA\n>ENST00000870733.1\nGTGCACGCTTCGGGTTGGTGTCATGGCAGCTGCGGGGAGCCGCAAGAGGCGCCTGGCGGA\nGCTGACGGTGGACGAGTTCCTAGCTTCGGGCTTTGACTCCGAGTCCGAATCCGAGTCCGA\nAAATTCTCCACAAGCGGAGACACGGGAAGCACGCGAGGCTGCCCGGAGTCCGGATAAGCC\nGGGCGGGAGCCCCTCGGCCAGCCGGCGTAAAGGCCGTGCCTCTGAGCACAAAGACCAGCT\nCTCTCGGCTGAAGGACAGAGACCCCGAGTTCTACAAGTTCCTGCAGGAGAATGACCAGAG\nCCTGCTAAACTTCAGCGACTCGGACAGCTCTGAGGAGGAAGAGGGGCCGTTCCACTCCCT\nGCCAGATGTGCTGGAGGAAGCCAGTGAGGAGGAGGATGGAGCGGAGGAAGGAGAAGATGG\nGGACAGAGTCCCCAGAGGGCTGAAGGGGAAGAAGAATTCTGTTCCTGTGACCGTCGCCAT\nGGTTGAGAGATGGAAGCAGGCAGCAAAGCAACGCCTCACTCCAAAGCTGTTCCATGAAGT\nGGTACAGGCGTTCCGAGCAGCTGTGGCCACCACCCGAGGGGACCAGGAAAGTGCTGAGGC\nCAACAAATTCCAGGTCACGGACAGTGCTGCATTCAATGCTCTGGTTACCTTCTGCATCAG\nAGACCTCATTGGCTGTCTCCAGAAGCTGCTGTTTGGAAAGGTGGCAAAGGATAGCAGCAG\nCAAATGTGGGCCAAAGGAAACCAGTCTGCGGCAGTTGGTGGTGCCTGGGCGACCCCAGAG\nGATGCTGCAGCCGTCCAGCAGCCCGCTCTGGGGGAAGCTTCGTGTGGACATCAAGGCTTA\nCCTGGGCTCGGCCATACAGCTGGTGTCCTGTCTGTCGGAGACGACGGTGTTGGCGGCCGT\nGCTGCGGCACATCAGCGTGCTGGTGCCCTGCTTCCTGACCTTCCCCAAGCAGTGCCGCAT\nGCTGCTCAAGAGAATGGTGATCGTATGGAGCACTGGGGAAGAGTCTCTGCGGGTGCTGGC\nTTTCCTGGTCCTCAGCAGAGTCTGCCGGCACAAGAAGGACACTTTCCTTGGCCCCGTCCT\nCAAGCAAATGTACATCACGTATGTGAGGAACTGCAAGTTCACCTCGCCTGGTGCCCTCCC\nCTTCATCAGTTTCATGCAGTGGACCTTGACGGAGCTGCTGGCCCTGGAGCCGGGTGTGGC\nCTACCAGCACGCCTTCCTCTACATCCGCCAGCTCGCCATACACCTGCGCAACGCCATGAC\nCACTCGCAAGAAGGAAACATACCAGTCTGTGTACAACTGGCAGTATGTGCACTGCCTCTT\nCCTGTGGTGCCGGGTCCTGAGCACTGCGGGCCCCAGCGAAGCCCTCCAGCCCTTGGTCTA\nCCCCCTTGCCCAAGTCATCATTGGCTGTATCAAGCTCATCCCCACTGCCCGCTTCTACCC\nGCTGCGAATGCACTGCATCCGTGCCCTGACGCTGCTCTCGGGGAGCTCGGGGGCCTTCAT\nCCCGGTGCTGCCTTTCATCCTGGAGGTCGACTTCAACAGGAAGCCAGGGCGCATGAGCTC\nCAAGCCCATCAACTTCTCCGTGATCCTGAAGCTGTCCAATGTCAACCTGCAGGAGAAGGC\nGTACCGGGACGGCCTGGTGGAGCAGCTGTACGACCTCACCCTGGAGTACCTGCACAGCCA\nGGCACACTGCATCGGCTTCCCGGAGCTGGTGCTGCCTGTGGTCCTGCAGCTGAAGTCGTT\nCCTCCGGGAGTGCAAGGTGGCCAACTACTGCCGGCAGGTGCAGCAGCTGCTTGGGAAGGT\nTCAGGAGAACTCGGCATACATCTGCAGCCGCCGCCAGAGGGTTTCCTTCGGCGTCTCTGA\nGCAGCAGGCAGTGGAAGCCTGGGAGAAGCTGACCCGGGAAGAGGGGACACCCCTGACCTT\nGTACTACAGCCACTGGCGCAAGCTGCGTGACCGGGAGATCCAGCTGGAGATCAGTGGCAA\nAGAGCGGCTGGAAGACCTGAACTTCCCTGAGATCAAACGAAGGAAGATGGCTGACAGGAA\nGGATGAGGACAGGAAGCAATTTAAAGACCTCTTTGACCTGAACAGCTCTGAAGAGGACGA\nCACCGAGGGATTCTCGGAGAGAGGGATACTGAGGCCCCTGAGCACTCGGCATGGGGTGGA\nAGACGATGAAGAGGACGAGGAGGAGGGCGAGGAGGACAGCAGCAACTCGGAGGATGGAGA\nCCCAGACGCAGAGGCGGGGCTGGCCCCTGGGGAGCTGCAGCAGCTGGCCCAGGGGCCGGA\nGGACGAGCTGGAGGATCTGCAGCTCTCAGAGGACGACTGAGGCAGCCCATCTGGGGGGCC\nTGTAGGGGCTGCCGGGCTGGTGGCCAGTGTTTCCACCTCCCTGGCAGTCAGGCCTAGAGG\nCTGGCGTCTGTGCAGTTGGGGGAGGCAGTAGACACGGGACAGGCTTTATTATTTATTTTT\nCAGCATGAAAGACCAAACGTATCGAGAGCTGGGCTGGGCTGGGCTGGTGTGGCTGCTGAA\nGCCCCACAGCTGTGGGCTGCTGAAGTCAGCTCCGCGGGGGAGCTGACCCTGACGTCAGCA\nGACCGAGACCAGTCCCAGTTCCAGGGGGAGGCCTGCAGGCCCCTGGCCCCTTCCACCACC\nTCTGCCCTCCGTCTGCAGACCTCGTCCATCTGCACCAGGCTCTGCCTTCACTCCCCCAAG\nTCTTTGAAAATTTGTTCCTTTCCTTTGAAGTCACATTTTCTTTTAAAATTTTTTGTTTTG\nCATCCGAAACCGAAAGAAATAAAGCGGTGGGAGGCAGGGCCATTGTGTT\n'

In [ ]:
import subprocess
import os
import tempfile

with tempfile.NamedTemporaryFile(mode='w', suffix='.fasta', delete=False, encoding='utf-8') as f:
    f.write(res)
    mrna_path = f.name

try:
    result = subprocess.run(
        [
            'python',
            './TarPmiR.py',
            '-a', './mirnaverified.fasta',
            '-b', mrna_path,
            '-m', './models/Human.pkl',
            '-p', '0.01'
        ],
        text=True,
        cwd='/home/nikos/ptixiaki/TarPmiR_Linux'
    )
finally:
    os.unlink(mrna_path)

In [4]:
import subprocess
import os
import requests
import tempfile
import logging
import re
from multiprocessing import Pool

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    filename='run.log',
    filemode='a'
)

def runTarpmir(idList):
    logging.info(f'PID{os.getpid()}: Starting')
    
    res = ''    
    for transcriptid in idList:
        res += requests.get(f'https://rest.ensembl.org/sequence/id/{transcriptid}?type=cdna', headers={"content-type":"text/x-fasta"}).text
    res = re.sub(r'(?m)^You.+connections', '', res) #NOTE: PREPEI NA FTIAKSO TO RATE LIMIT KAPOS
        
    logging.info(f'PID{os.getpid()}: Transcript GET completed')
        
    with tempfile.NamedTemporaryFile(mode='w', suffix='.fasta', delete=False, encoding='utf-8') as f:
        f.write(res)
        mrna_path = f.name


    try:
        logging.info(f'PID{os.getpid()}: Starting TarPmiR with tempfile {mrna_path}')
        result = subprocess.run(
            [
                'python',
                './TarPmiR.py',
                '-a', './mirnaverified.fasta',
                '-b', mrna_path,
                '-m', './models/Human.pkl',
                '-p', '0.01'
            ],
            text=True,
            cwd='/home/nikos/ptixiaki/TarPmiR_Linux',
            capture_output=True,
            check=True
        )
        logging.info(f'PID{os.getpid()}: TarPmiR completed')
    except subprocess.CalledProcessError as e:
        logging.error(f'PID{os.getpid()}: TarPmiR failed with return code {e.returncode} using tempfile {mrna_path}:\n{e.stderr}')
    except Exception as e:
        logging.error(f'PID{os.getpid()}: Exception occurred: {e}')
    # finally:
    #     os.unlink(mrna_path)
        

def chunkify(idList, chunkNum):
    chunk_size = len(idList) // chunkNum
    chunks = [idList[i*chunk_size:(i+1)*chunk_size] for i in range(chunkNum)]

    if len(idList) % chunkNum != 0:
        chunks[-1].extend(idList[chunkNum*chunk_size:])
    return chunks


def batchTarPmiR(idList, processNum):
    logging.info(f'STARTING BATCH PROCESS WITH {processNum} PROCESSES')
    with Pool(processes=processNum) as pool:
        pool.map(runTarpmir, chunkify(idList, processNum))
    logging.info(f'FINISHED BATCH PROCESS')

In [5]:
batchTarPmiR(transcripts[:5000], 22)

In [9]:
def testTarPmiR():
    try:
        result = subprocess.run(
            [
                'python',
                './TarPmiR.py',
                '-a', './mirnaverified.fasta',
                '-b', './cDNA.fasta',
                '-m', './models/Human_sklearn_0.22.pkl',
                '-p', '0.5'
            ],
            text=True,
            cwd='/home/nikos/ptixiaki/TarPmiR_Linux',
            capture_output=True,
            check=True
        )
        logging.info(f'PID{os.getpid()}: TarPmiR completed')
    except subprocess.CalledProcessError as e:
        logging.error(f'PID{os.getpid()}: TarPmiR failed with return code {e.returncode}:\n{e.stderr}')
    except Exception as e:
        logging.error(f'PID{os.getpid()}: Exception occurred: {e}')